id: e132306b833047c586e8ea86147cb1d5
initial_creation_type: ocr
source_metadata:
  volumes:
    23be24e1141c463a858f3fe2e8102a1b:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: མཎྜལ་གྱི་ཆོ་ག།
      total_pages: 1902
      volume_number: 26
